version: '3.9'

services:
  grav:
    container_name: grav
    image: ghcr.io/linuxserver/grav
    environment:
      - TZ=Asia/Kuching
      - PUID=1026
      - PGID=100
    volumes:
      - /data/grav:/config
    ports:
      - 80:80
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    